// A local list of NSE stock symbols for search autocomplete - no API
// calls needed, works instantly as the user types.
export const stockList = [
  // Note: each entry below also needs a "sector" field added - see the
  // sectorizedStockList export at the bottom of this file, which is
  // generated automatically from this same data plus a lookup table.
  // IT
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "LTIM", name: "LTIMindtree" },
  { symbol: "LTM", name: "LTM Limited" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "MPHASIS", name: "MphasiS" },
  { symbol: "LTTS", name: "L&T Technology Services" },
  { symbol: "OFSS", name: "Oracle Financial Services Software" },
  { symbol: "TATATECH", name: "Tata Technologies" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "HEXT", name: "Hexaware Technologies" },
  { symbol: "KPITTECH", name: "KPIT Technologies" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies" },
  { symbol: "BSOFT", name: "Birlasoft" },
  { symbol: "SONATSOFTW", name: "Sonata Software" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies" },
  { symbol: "INTELLECT", name: "Intellect Design Arena" },
  { symbol: "MASTEK", name: "Mastek" },
  { symbol: "CYIENT", name: "Cyient" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics" },
  { symbol: "TANLA", name: "Tanla Platforms" },
  { symbol: "RATEGAIN", name: "Rategain Travel Technologies" },
  { symbol: "EMUDHRA", name: "eMudhra" },
  { symbol: "DATAMATICS", name: "Datamatics Global Services" },

  // Banking
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "UNIONBANK", name: "Union Bank of India" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank" },
  { symbol: "FEDERALBNK", name: "Federal Bank" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "AUBANK", name: "AU Small Finance Bank" },
  { symbol: "YESBANK", name: "Yes Bank" },
  { symbol: "RBLBANK", name: "RBL Bank" },
  { symbol: "INDIANB", name: "Indian Bank" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra" },

  // Financial Services / NBFC / Insurance
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance" },
  { symbol: "PFC", name: "Power Finance Corporation" },
  { symbol: "RECLTD", name: "REC Limited" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance" },
  { symbol: "SBICARD", name: "SBI Cards and Payment Services" },
  { symbol: "PAISALO", name: "Paisalo Digital" },
  { symbol: "LICI", name: "Life Insurance Corporation" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management" },
  { symbol: "IEX", name: "Indian Energy Exchange" },
  { symbol: "MCX", name: "Multi Commodity Exchange" },
  { symbol: "BSE", name: "BSE Limited" },
  { symbol: "ANGELONE", name: "Angel One" },
  { symbol: "CDSL", name: "Central Depository Services" },

  // Oil, Gas & Energy
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation" },
  { symbol: "IOC", name: "Indian Oil Corporation" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum" },
  { symbol: "GAIL", name: "GAIL India" },
  { symbol: "OIL", name: "Oil India" },
  { symbol: "PETRONET", name: "Petronet LNG" },
  { symbol: "IGL", name: "Indraprastha Gas" },
  { symbol: "MGL", name: "Mahanagar Gas" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas" },

  // Power / Utilities
  { symbol: "NTPC", name: "NTPC" },
  { symbol: "POWERGRID", name: "Power Grid Corporation" },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions" },
  { symbol: "NHPC", name: "NHPC" },
  { symbol: "SJVN", name: "SJVN" },
  { symbol: "TATATECH", name: "Tata Technologies" },
  { symbol: "JSWENERGY", name: "JSW Energy" },
  { symbol: "TORNTPOWER", name: "Torrent Power" },
  { symbol: "CESC", name: "CESC" },

  // Metals & Mining
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "VEDL", name: "Vedanta" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "SAIL", name: "Steel Authority of India" },
  { symbol: "NMDC", name: "NMDC" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power" },
  { symbol: "NATIONALUM", name: "National Aluminium Company" },
  { symbol: "HINDZINC", name: "Hindustan Zinc" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes" },

  // Cement & Construction
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "ACC", name: "ACC Limited" },
  { symbol: "SHREECEM", name: "Shree Cement" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat" },
  { symbol: "JKCEMENT", name: "JK Cement" },
  { symbol: "RAMCOCEM", name: "Ramco Cements" },

  // Infrastructure / Capital Goods
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "ABB", name: "ABB India" },
  { symbol: "CUMMINSIND", name: "Cummins India" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "BHEL", name: "BHEL" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard" },
  { symbol: "IRCON", name: "IRCON International" },
  { symbol: "RVNL", name: "Rail Vikas Nigam" },
  { symbol: "IRFC", name: "Indian Railway Finance Corp" },
  { symbol: "CONCOR", name: "Container Corporation of India" },

  // Auto
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries" },
  { symbol: "MRF", name: "MRF" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres" },
  { symbol: "CEATLTD", name: "CEAT" },
  { symbol: "BOSCHLTD", name: "Bosch" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "EXIDEIND", name: "Exide Industries" },
  { symbol: "TIINDIA", name: "Tube Investments of India" },

  // Pharma & Healthcare
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "LUPIN", name: "Lupin" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences" },
  { symbol: "ALKEM", name: "Alkem Laboratories" },
  { symbol: "MANKIND", name: "Mankind Pharma" },
  { symbol: "BIOCON", name: "Biocon" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals" },
  { symbol: "IPCALAB", name: "Ipca Laboratories" },
  { symbol: "LAURUSLABS", name: "Laurus Labs" },
  { symbol: "GRANULES", name: "Granules India" },
  { symbol: "FORTIS", name: "Fortis Healthcare" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs" },

  // FMCG
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "ITC", name: "ITC Limited" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "DABUR", name: "Dabur India" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products" },
  { symbol: "MARICO", name: "Marico" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "VBL", name: "Varun Beverages" },
  { symbol: "UBL", name: "United Breweries" },
  { symbol: "UNITDSPR", name: "United Spirits" },
  { symbol: "EMAMILTD", name: "Emami" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene" },
  { symbol: "PATANJALI", name: "Patanjali Foods" },

  // Retail / Consumer Durables
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "DMART", name: "Avenue Supermarts" },
  { symbol: "TRENT", name: "Trent" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "BERGEPAINT", name: "Berger Paints" },
  { symbol: "PIDILITIND", name: "Pidilite Industries" },
  { symbol: "HAVELLS", name: "Havells India" },
  { symbol: "VOLTAS", name: "Voltas" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India" },
  { symbol: "BLUESTARCO", name: "Blue Star" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics" },
  { symbol: "RELAXO", name: "Relaxo Footwears" },
  { symbol: "BATAINDIA", name: "Bata India" },
  { symbol: "PAGEIND", name: "Page Industries" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail" },
  { symbol: "VMART", name: "V-Mart Retail" },

  // Telecom
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "IDEA", name: "Vodafone Idea" },
  { symbol: "INDUSTOWER", name: "Indus Towers" },

  // New-age Tech / Internet
  { symbol: "ZOMATO", name: "Eternal (Zomato)" },
  { symbol: "NYKAA", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "PAYTM", name: "One97 Communications (Paytm)" },
  { symbol: "POLICYBZR", name: "PB Fintech (Policybazaar)" },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism" },
  { symbol: "DELHIVERY", name: "Delhivery" },
  { symbol: "MAPMYINDIA", name: "C.E. Info Systems" },
  { symbol: "SHIPROCKET", name: "Shiprocket" },
  { symbol: "IKS", name: "Inventurus Knowledge Solutions" },

  // Chemicals
  { symbol: "PIIND", name: "PI Industries" },
  { symbol: "SRF", name: "SRF Limited" },
  { symbol: "UPL", name: "UPL Limited" },
  { symbol: "AARTIIND", name: "Aarti Industries" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International" },
  { symbol: "ATUL", name: "Atul Limited" },
  { symbol: "TATACHEM", name: "Tata Chemicals" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers" },
  { symbol: "COROMANDEL", name: "Coromandel International" },

  // Real Estate
  { symbol: "DLF", name: "DLF Limited" },
  { symbol: "GODREJPROP", name: "Godrej Properties" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills" },
  { symbol: "LODHA", name: "Macrotech Developers (Lodha)" },

  // Media & Entertainment
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises" },
  { symbol: "SUNTV", name: "Sun TV Network" },
  { symbol: "PVRINOX", name: "PVR INOX" },
  { symbol: "NAZARA", name: "Nazara Technologies" },

  // Textiles
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "TRIDENT", name: "Trident Limited" },
  { symbol: "RAYMOND", name: "Raymond" },
  { symbol: "WELSPUNLIV", name: "Welspun Living" },

  // Miscellaneous large caps
  { symbol: "ADANIGREEN", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "ADANITRANS", name: "Adani Transmission" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)" },
  { symbol: "SPICEJET", name: "SpiceJet" },
  { symbol: "GMRAIRPORT", name: "GMR Airports" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks" },
  { symbol: "DEVYANI", name: "Devyani International" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India" },
  { symbol: "NETWEB", name: "Netweb Technologies" },
  { symbol: "AFFLE", name: "Affle 3i" },
  { symbol: "E2E", name: "E2E Networks" },
  { symbol: "TATATECH", name: "Tata Technologies" },
];
// Sector grouping for the "browse by sector" feature. Maps each symbol
// to a sector name - built separately from stockList above so we didn't
// have to rewrite every existing entry.
const SECTOR_MAP = {
  "Information Technology": ["TCS","INFY","HCLTECH","WIPRO","TECHM","LTIM","LTM","PERSISTENT","COFORGE","MPHASIS","LTTS","OFSS","TATATECH","TATAELXSI","HEXT","KPITTECH","ZENSARTECH","BSOFT","SONATSOFTW","NEWGEN","INTELLECT","MASTEK","CYIENT","HAPPSTMNDS","LATENTVIEW","TANLA","RATEGAIN","EMUDHRA","DATAMATICS"],
  "Banking": ["HDFCBANK","ICICIBANK","SBIN","KOTAKBANK","AXISBANK","INDUSINDBK","PNB","BANKBARODA","CANBK","UNIONBANK","IDFCFIRSTB","FEDERALBNK","BANDHANBNK","AUBANK","YESBANK","RBLBANK","INDIANB","MAHABANK"],
  "Financial Services": ["BAJFINANCE","BAJAJFINSV","SBILIFE","HDFCLIFE","ICICIPRULI","ICICIGI","SHRIRAMFIN","CHOLAFIN","MUTHOOTFIN","PFC","RECLTD","LICHSGFIN","SBICARD","PAISALO","LICI","HDFCAMC","IEX","MCX","BSE","ANGELONE","CDSL"],
  "Oil, Gas & Energy": ["RELIANCE","ONGC","IOC","BPCL","HINDPETRO","GAIL","OIL","PETRONET","IGL","MGL","GUJGASLTD"],
  "Power & Utilities": ["NTPC","POWERGRID","TATAPOWER","ADANIPOWER","ADANIENSOL","NHPC","SJVN","JSWENERGY","TORNTPOWER","CESC"],
  "Metals & Mining": ["TATASTEEL","JSWSTEEL","HINDALCO","VEDL","COALINDIA","SAIL","NMDC","JINDALSTEL","NATIONALUM","HINDZINC","APLAPOLLO"],
  "Cement & Construction": ["ULTRACEMCO","AMBUJACEM","ACC","SHREECEM","DALBHARAT","JKCEMENT","RAMCOCEM"],
  "Infrastructure & Capital Goods": ["LT","ADANIPORTS","ADANIENT","SIEMENS","ABB","CUMMINSIND","BEL","HAL","BHEL","GRSE","COCHINSHIP","IRCON","RVNL","IRFC","CONCOR"],
  "Automobile": ["MARUTI","TATAMOTORS","M&M","BAJAJ-AUTO","EICHERMOT","HEROMOTOCO","TVSMOTOR","ASHOKLEY","BALKRISIND","MRF","APOLLOTYRE","CEATLTD","BOSCHLTD","MOTHERSON","EXIDEIND","TIINDIA"],
  "Pharma & Healthcare": ["SUNPHARMA","DRREDDY","CIPLA","DIVISLAB","APOLLOHOSP","LUPIN","AUROPHARMA","TORNTPHARM","ZYDUSLIFE","ALKEM","MANKIND","BIOCON","GLENMARK","IPCALAB","LAURUSLABS","GRANULES","FORTIS","MAXHEALTH","METROPOLIS","LALPATHLAB"],
  "FMCG": ["HINDUNILVR","ITC","NESTLEIND","BRITANNIA","DABUR","GODREJCP","MARICO","COLPAL","TATACONSUM","VBL","UBL","UNITDSPR","EMAMILTD","PGHH","PATANJALI"],
  "Retail & Consumer Durables": ["TITAN","DMART","TRENT","ASIANPAINT","BERGEPAINT","PIDILITIND","HAVELLS","VOLTAS","WHIRLPOOL","BLUESTARCO","CROMPTON","KAJARIACER","RELAXO","BATAINDIA","PAGEIND","ABFRL","VMART"],
  "Telecom": ["BHARTIARTL","IDEA","INDUSTOWER"],
  "New-age Tech & Internet": ["ZOMATO","NYKAA","PAYTM","POLICYBZR","IRCTC","DELHIVERY","MAPMYINDIA","SHIPROCKET","IKS","NETWEB","AFFLE","E2E"],
  "Chemicals": ["PIIND","SRF","UPL","AARTIIND","DEEPAKNTR","NAVINFLUOR","ATUL","TATACHEM","GNFC","COROMANDEL"],
  "Real Estate": ["DLF","GODREJPROP","OBEROIRLTY","PRESTIGE","PHOENIXLTD","LODHA"],
  "Media & Entertainment": ["ZEEL","SUNTV","PVRINOX","NAZARA"],
  "Textiles": ["GRASIM","TRIDENT","RAYMOND","WELSPUNLIV"],
  "Aviation & Others": ["INDIGO","SPICEJET","GMRAIRPORT","JUBLFOOD","DEVYANI","SAPPHIRE"],
};

export const sectorNames = Object.keys(SECTOR_MAP);

export function getStocksBySector(sector) {
  const symbols = SECTOR_MAP[sector] || [];
  return symbols
    .map((symbol) => stockList.find((s) => s.symbol === symbol))
    .filter(Boolean);
}
