// A local list of NSE stock symbols for search autocomplete - no API
// calls needed, works instantly as the user types. Add more symbols
// over time as needed.
export const stockList = [
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "TATATECH", name: "Tata Technologies" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "ITC", name: "ITC Limited" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" },
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "POWERGRID", name: "Power Grid Corporation" },
  { symbol: "NTPC", name: "NTPC Limited" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "DABUR", name: "Dabur India" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products" },
  { symbol: "PIDILITIND", name: "Pidilite Industries" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "IOC", name: "Indian Oil Corporation" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "VEDL", name: "Vedanta Limited" },
  { symbol: "ZOMATO", name: "Zomato" },
  { symbol: "NYKAA", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "PAYTM", name: "One97 Communications (Paytm)" },
  { symbol: "IRCTC", name: "Indian Railway Catering" },
  { symbol: "DMART", name: "Avenue Supermarts (DMart)" },
  { symbol: "TRENT", name: "Trent Limited" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "MPHASIS", name: "MphasiS" },
  { symbol: "LTIM", name: "LTIMindtree" },
];
